# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HealthSIG
                                 A QGIS plugin
 Add layer with health services
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-16
        copyright            : (C) 2019 by Tiago Lima
        email                : tiagoal_25@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HealthSIG class from file HealthSIG.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .health_sig import HealthSIG
    return HealthSIG(iface)
